### ISSUE TITLE
bug: Incorrect Beak Placement

### ISSUE THREAD

**Issue by Kronifer** [python-discord/quackstack#63]
I've noticed that the bottom beak is layered incorrectly. Has this been noticed? I've attached an example below.

![image](https://user-images.githubusercontent.com/44979306/132111929-8e800558-af65-41e8-9b6d-bdfc7e6377c1.png)

**Comment by Shivansh-007** [comment]
Hi @Kronifer,

Thanks for the report, a bug in my code 😔. Well the bug is here: https://github.com/python-discord/quackstack/blob/c7ace24fb0ef852d65bf912a011f8520a64b1342/quackstack/ducky.py#L43-L47

Where `beak` should be placed above `body` (the list is in the order it would get built), as `beak` is supposed to be under `body`. A quick PR would be appreciated.

**Comment by Shivansh-007** [comment]
Alec was real quick 💨
